ENGINEERING_EVENTS = {
    "SUBMITTAL_SUBMITTED": "engineering.submittal.submitted",
    "SUBMITTAL_APPROVED": "engineering.submittal.approved",
    "SUBMITTAL_REJECTED": "engineering.submittal.rejected",
    "SUBMITTAL_RESUBMITTED": "engineering.submittal.resubmitted",
    "SUBMITTAL_CLOSED": "engineering.submittal.closed",
    "INSPECTION_SUBMITTED": "engineering.inspection.submitted",
    "INSPECTION_PASSED": "engineering.inspection.passed",
    "INSPECTION_FAILED": "engineering.inspection.failed",
    "INSPECTION_REINSPECTED": "engineering.inspection.reinspected",
    "PUNCHLIST_STARTED": "engineering.punchlist.started",
    "PUNCHLIST_COMPLETED": "engineering.punchlist.completed",
    "PUNCHLIST_VERIFIED": "engineering.punchlist.verified",
    "PUNCHLIST_ACCEPTED": "engineering.punchlist.accepted",
    "PUNCHLIST_REOPENED": "engineering.punchlist.reopened",
    "TRANSMITTAL_SENT": "engineering.transmittal.sent",
    "TRANSMITTAL_RECEIVED": "engineering.transmittal.received",
    "TRANSMITTAL_ACKNOWLEDGED": "engineering.transmittal.acknowledged",
    "TRANSMITTAL_CLOSED": "engineering.transmittal.closed",
    "SAFETY_INCIDENT_INVESTIGATED": "engineering.safety_incident.investigated",
    "SAFETY_INCIDENT_ACTION_TAKEN": "engineering.safety_incident.action_taken",
    "SAFETY_INCIDENT_CLOSED": "engineering.safety_incident.closed",
    "SAFETY_OBSERVATION_ACKNOWLEDGED": "engineering.safety_observation.acknowledged",
    "SAFETY_OBSERVATION_RESOLVED": "engineering.safety_observation.resolved",
    "SAFETY_OBSERVATION_CLOSED": "engineering.safety_observation.closed",
}
