"""add_engineering_features_and_token_blacklist

Revision ID: 89e3127f15a0
Revises: 76e9ce3563fc
Create Date: 2026-06-17 10:55:38.738915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e3127f15a0'
down_revision: Union[str, Sequence[str], None] = '76e9ce3563fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_table('boq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['boq_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boq_items_id'), 'boq_items', ['id'], unique=False)
    op.create_index(op.f('ix_boq_items_item_code'), 'boq_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_boq_items_project_id'), 'boq_items', ['project_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('party_a', sa.String(length=255), nullable=False),
    sa.Column('party_b', sa.String(length=255), nullable=False),
    sa.Column('sign_date', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('retention_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('advance_payment_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=True),
    sa.Column('manpower_count', sa.Integer(), nullable=False),
    sa.Column('equipment_count', sa.Integer(), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reports_id'), 'daily_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_reports_project_id'), 'daily_reports', ['project_id'], unique=False)
    op.create_table('eng_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eng_documents_id'), 'eng_documents', ['id'], unique=False)
    op.create_index(op.f('ix_eng_documents_project_id'), 'eng_documents', ['project_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_project_id'), 'schedules', ['project_id'], unique=False)
    op.create_table('subcontractors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractors_id'), 'subcontractors', ['id'], unique=False)
    op.create_index(op.f('ix_subcontractors_project_id'), 'subcontractors', ['project_id'], unique=False)
    op.create_table('ipc_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('ipc_number', sa.String(length=50), nullable=False),
    sa.Column('ipc_period', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('retention_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('advance_recovery', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipc_headers_contract_id'), 'ipc_headers', ['contract_id'], unique=False)
    op.create_index(op.f('ix_ipc_headers_id'), 'ipc_headers', ['id'], unique=False)
    op.create_index(op.f('ix_ipc_headers_ipc_number'), 'ipc_headers', ['ipc_number'], unique=False)
    op.create_index(op.f('ix_ipc_headers_project_id'), 'ipc_headers', ['project_id'], unique=False)
    op.create_table('ipc_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipc_id', sa.Integer(), nullable=False),
    sa.Column('boq_item_id', sa.Integer(), nullable=False),
    sa.Column('previous_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cumulative_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('boq_item_code', sa.String(length=50), nullable=True),
    sa.Column('boq_item_description', sa.Text(), nullable=True),
    sa.Column('boq_item_unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ),
    sa.ForeignKeyConstraint(['ipc_id'], ['ipc_headers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipc_details_boq_item_id'), 'ipc_details', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_ipc_details_id'), 'ipc_details', ['id'], unique=False)
    op.create_index(op.f('ix_ipc_details_ipc_id'), 'ipc_details', ['ipc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipc_details_ipc_id'), table_name='ipc_details')
    op.drop_index(op.f('ix_ipc_details_id'), table_name='ipc_details')
    op.drop_index(op.f('ix_ipc_details_boq_item_id'), table_name='ipc_details')
    op.drop_table('ipc_details')
    op.drop_index(op.f('ix_ipc_headers_project_id'), table_name='ipc_headers')
    op.drop_index(op.f('ix_ipc_headers_ipc_number'), table_name='ipc_headers')
    op.drop_index(op.f('ix_ipc_headers_id'), table_name='ipc_headers')
    op.drop_index(op.f('ix_ipc_headers_contract_id'), table_name='ipc_headers')
    op.drop_table('ipc_headers')
    op.drop_index(op.f('ix_subcontractors_project_id'), table_name='subcontractors')
    op.drop_index(op.f('ix_subcontractors_id'), table_name='subcontractors')
    op.drop_table('subcontractors')
    op.drop_index(op.f('ix_schedules_project_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_eng_documents_project_id'), table_name='eng_documents')
    op.drop_index(op.f('ix_eng_documents_id'), table_name='eng_documents')
    op.drop_table('eng_documents')
    op.drop_index(op.f('ix_daily_reports_project_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_id'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_boq_items_project_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_item_code'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_id'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
